[workspace]
members = ["src/grader",
	"src/lab", "src/runner", "src/suite", "src/grader"
]
resolver = "2"

[workspace.dependencies]
lab = { path = "src/lab" }
runner = { path = "src/runner" }
suite = { path = "src/suite" }
grader = { path = "src/grader" }

