[workspace]
members = ["src/grader",
	"src/lab", "src/runner", "src/suite", "src/grader"
	, "src/util"]
default-members = ["src/grader"] # 默认主项目

resolver = "2"

[workspace.dependencies]
lab = { path = "src/lab" }
runner = { path = "src/runner" }
suite = { path = "src/suite" }
grader = { path = "src/grader" }
util = { path = "src/util" }
pyo3 = { version = "0.23.5", features = ["auto-initialize", "generate-import-lib"] }
