[workspace]
members = ["crates/grader",
	"crates/lab", "crates/runner", "crates/suite", "crates/grader"
	, "crates/util", "crates/common"]
default-members = ["crates/grader"] # 默认主项目

resolver = "2"

[workspace.dependencies]
lab = { path = "crates/lab" }
runner = { path = "crates/runner" }
suite = { path = "crates/suite" }
grader = { path = "crates/grader" }
util = { path = "crates/util" }
pyo3 = { version = "0.23.5", features = ["auto-initialize", "generate-import-lib"] }
