[package]
name = "code_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-builder = "0.21.0"
pyo3 = { version = "0.24.2", features = ["generate-import-lib", "auto-initialize"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
derivative = "2.2.0"
