[package]
name = "lab"
version = "0.1.0"
edition = "2021"

[dependencies]
runner.workspace = true
suite.workspace = true
util.workspace = true
lazy_static = "1.5.0"
log = "0.4.26"
pyo3.workspace = true
strum = "0.27.1"
strum_macros = "0.27.1"
