[package]
name = "lab"
version = "0.1.0"
edition = "2021"

[dependencies]
runner.workspace = true
suite.workspace = true
util.workspace = true
lazy_static = "1.5.0"
strum = "0.27.1"
strum_macros = "0.27.1"
itertools = "0.14.0"
