[package]
name = "labs"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
common.workspace = true
code_runner.workspace = true
dev.workspace = true
scraper = "0.23.1"
tempfile = "3.19.1"
